# Generated by Django 5.0.6 on 2024-06-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voyage',
        ),
    ]
