# Generated by Django 5.0.6 on 2024-06-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_size',
            field=models.PositiveBigIntegerField(),
        ),
    ]
