# Generated by Django 5.0.6 on 2024-07-01 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_uploadfile_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='name',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 10, 34, 3, 871129, tzinfo=datetime.timezone.utc)),
        ),
    ]
