# Generated by Django 5.0.6 on 2024-07-01 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_remove_uploadfile_email_remove_uploadfile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='download_link',
            field=models.CharField(default='veHI3h5', editable=False, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 11, 21, 44, 739140, tzinfo=datetime.timezone.utc)),
        ),
    ]
