# Generated by Django 5.0.6 on 2024-07-01 12:16

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_uploadfile_download_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='delete_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='download_link',
            field=models.CharField(default='nCWO5nx', editable=False, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 12, 16, 17, 382508, tzinfo=datetime.timezone.utc)),
        ),
    ]
