# Generated by Django 5.0.6 on 2024-07-01 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_uploadfile_delete_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='download_link',
            field=models.CharField(default='NKUZNpl', editable=False, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 12, 29, 26, 787019, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_by',
            field=models.CharField(default='Guest', max_length=255),
        ),
    ]
