# Generated by Django 5.0.6 on 2024-07-01 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_alter_uploadfile_download_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='download_link',
            field=models.CharField(editable=False, max_length=7),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 15, 18, 45, 363676, tzinfo=datetime.timezone.utc)),
        ),
    ]
