# Generated by Django 5.0.6 on 2024-07-03 22:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_remove_uploadfile_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 4, 22, 10, 58, 604031, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
