# Generated by Django 5.0.6 on 2024-07-04 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_alter_uploadfile_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 13, 16, 52, 906184, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
