# Generated by Django 5.0.6 on 2024-07-08 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0018_deletedfile_download_link_expiredfile_download_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 9, 5, 31, 940867, tzinfo=datetime.timezone.utc)),
        ),
    ]
